// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmxgbeQjV0V-O5wV5mdoZ6Snpszupy2g4',
    appId: '1:667085431035:web:655682d709695e5823d05e',
    messagingSenderId: '667085431035',
    projectId: 'photo-like-92bf0',
    authDomain: 'photo-like-92bf0.firebaseapp.com',
    storageBucket: 'photo-like-92bf0.appspot.com',
    measurementId: 'G-PG0JD47L5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhQ-wl66kg73UzUfZzLt2PXYv77Kb2kc',
    appId: '1:667085431035:android:5c7e438aec31770f23d05e',
    messagingSenderId: '667085431035',
    projectId: 'photo-like-92bf0',
    storageBucket: 'photo-like-92bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2M3fCl-Hxtyr6MlxHjK5dwbRlx7m3A8',
    appId: '1:667085431035:ios:65636686762b48d823d05e',
    messagingSenderId: '667085431035',
    projectId: 'photo-like-92bf0',
    storageBucket: 'photo-like-92bf0.appspot.com',
    iosClientId: '667085431035-d8n3maj7fbprmj3qhsjsti3h0um0cpee.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoLikeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC2M3fCl-Hxtyr6MlxHjK5dwbRlx7m3A8',
    appId: '1:667085431035:ios:65636686762b48d823d05e',
    messagingSenderId: '667085431035',
    projectId: 'photo-like-92bf0',
    storageBucket: 'photo-like-92bf0.appspot.com',
    iosClientId: '667085431035-d8n3maj7fbprmj3qhsjsti3h0um0cpee.apps.googleusercontent.com',
    iosBundleId: 'com.example.photoLikeApp',
  );
}
